# Generated by Django 5.2 on 2026-05-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_price_product_category_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='products.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Saída de Estoque',
                'verbose_name_plural': 'Saídas de Estoque',
            },
        ),
    ]
