# Generated by Django 5.2 on 2026-05-12 03:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_parent'),
        ('products', '0004_product_catalog_category_product_show_in_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCatalogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_pedido', models.CharField(max_length=20, unique=True, verbose_name='Número do Pedido')),
                ('cliente_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Cliente')),
                ('cliente_telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Cliente')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando Confirmação'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Pedido do Catálogo',
                'verbose_name_plural': 'Pedidos do Catálogo',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='catalog.pedidocatalogo', verbose_name='Pedido')),
            ],
        ),
    ]
