# Generated by Django 5.2 on 2026-05-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'Pix'), ('cash', 'Dinheiro'), ('card', 'Cartão'), ('other', 'Outro')], default='pix', max_length=20, verbose_name='Método de Pagamento'),
        ),
    ]
