# Generated by Django 5.2 on 2026-05-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_is_paid_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='installments',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Parcelas'),
        ),
    ]
