# Generated by Django 5.2 on 2026-05-09 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '__first__'),
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catalog_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Categoria do Catálogo'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_in_catalog',
            field=models.BooleanField(default=False, verbose_name='Exibir no catálogo?'),
        ),
    ]
