# Generated by Django 5.2 on 2026-05-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_category_name_unique_per_parent'),
        ('products', '0004_product_catalog_category_product_show_in_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catalog_category',
        ),
        migrations.AddField(
            model_name='product',
            name='catalog_categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.category', verbose_name='Categorias do Catálogo'),
        ),
    ]
